version: '3.8'
services:
  wirebill_postgress:
    container_name: wirebill_postgress
    image: postgres:latest
    env_file:
      - ../.env.$NODE_ENV
    ports:
      - 5432:5432
    volumes:
      - wirebill_postgress_data:/data/db
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - wirebill_network
    restart: unless-stopped

  wirebill_adminer:
    container_name: wirebill_adminer
    image: adminer
    restart: unless-stopped
    ports:
      - 9999:8080
    networks:
      - wirebill_network  

volumes:
  wirebill_postgress_data:

networks:
  wirebill_network:
    driver: bridge

